### ISSUE TITLE
Consider Name Change

### ISSUE THREAD

**Issue by set808** [tomy0000000/coon#2]
In case you weren't aware, Coon is a culturally inappropriate term in the US.

**Comment by tomy0000000** [comment]
Sorry for any uncomfortable feeling you (or anyone) might have.
As I name this project from many other similar phrases,
such as "coin",
"con-" for "conversion",
"cone🍦" for praising one of the best food on Earth,
I make no mean to insult or harm anyone.
Therefore, I've made up my mind to keep the naming,
apologize if this isn't your favor.
