### ISSUE TITLE
Show amounts for base currency to favorited currencies.

### ISSUE THREAD

**Issue by donileo** [tomy0000000/Coon#4]
Is there a way to show the conversion from x units of your base currency to all the currencies you have added as favorites. It seems the reverse is the default.

So if I specify cur 200 and my base currency is USD I want to see how much is 200 USD in all my other currencies.

**Comment by tomy0000000** [comment]
Please try the latest version and reply if that's what you're looking for.

**Comment by donileo** [comment]
Looks good. Is there any way to sort the results?

**Comment by tomy0000000** [comment]
Check out the [Setting & Help Methods](https://github.com/tomy0000000/Coon#setting--help-methods) section which has an animated gif telling you how do achieve that.
