### ISSUE TITLE
Support for Number Input with Comma

### ISSUE THREAD

**Issue by yif-li** [tomy0000000/Coon#6]
Since we always input the numbers with comma(s) from bank transactions, financial sheets, or technical reports. It would be better to support the input with comma(s). 

It works well w/o comma(s):

<img width="605" alt="Image Copied on 2020-02-18 at 21 19 48 PM" src="https://user-images.githubusercontent.com/32441766/74740900-c57b8500-5296-11ea-8235-f62182da34fa.png">

It fails w/ comma(s):

<img width="605" alt="Image Copied on 2020-02-18 at 21 19 48 PM" src="https://user-images.githubusercontent.com/32441766/74740913-cad8cf80-5296-11ea-945d-fb83148c9868.png">

**Comment by tomy0000000** [comment]
Thanks for the suggestion,
a new parser support comma and dollar signs is already in working progress.
Stay tuned for upcoming release expected in few weeks.

**Comment by yif-li** [comment]
Thanks! Just a friendly reminder: the position of the comma is different case by case. For instance, in the US the comma is set for each three-digit while in mainland China it's for each four-digit.

Therefore, simply skipping the commas or any other methods that take into account the position should be good.

**Comment by tomy0000000** [comment]
@yif-li 

v1.2.0 has just released,
go ahead and try if this meets your need.

Thoughts, issues, bug reports...etc are welcome 😉

**Comment by tomy0000000** [comment]
I'll take thumbs up as a sign off.
Incase if you have any further suggestion,
feel free to reopen or add new issues
